
create table users
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key(id)
);

create table menu
(
    id bigint generated by default as identity,
    parent_id bigint,
    name varchar(255),
    list_order int,
    user_id bigint,
    primary key(id),
    foreign key (parent_id) references menu(id),
    foreign key (user_id) references users(id)
);





DROP TABLE IF EXISTS Products;

CREATE TABLE Products
(
    prod_id     IDENTITY        PRIMARY KEY,
    prod_name   VARCHAR(255)    NOT NULL,
    prod_price  INT             NOT NULL
);

-- 회원
DROP TABLE IF EXISTS MB_MBR;

-- 회원
CREATE TABLE "MB_MBR" (
	"MBR_ID"    IDENTITY        PRIMARY KEY, -- 회원식별번호
	"MBR_NM"    VARCHAR(50) NOT NULL, -- 회원이름
	"MBR_CP_NO" VARCHAR(30) NOT NULL, -- 회원연락처
	"REG_DT"    DATETIME        NOT NULL, -- 등록일시
	"MOD_DT"    DATETIME        NULL      -- 수정일시
);


